### ISSUE TITLE
Bug therankshop

### ISSUE THREAD

**Issue by xlXlSlayerlXlx** [supercrafter333/theRankShop#17]
Server dies when buying rank, downloaded on poggit and GitHub and same error

**Comment by supercrafter333** [comment]
Please send the error/chrashdump.

**Comment by xlXlSlayerlXlx** [comment]
[Sat_Jul_1-16.37.47-UTC_2023.log](https://github.com/supercrafter333/theRankShop/files/11926677/Sat_Jul_1-16.37.47-UTC_2023.log)

**Comment by xlXlSlayerlXlx** [comment]
Any rank created happens this and even worse

**Comment by supercrafter333** [comment]
This is your fault. You're trying to add a non-existing rank to your rankshop.

**Comment by xlXlSlayerlXlx** [comment]
Dependency? Where do I create?
