### ISSUE TITLE
Prince serve  close error

### ISSUE THREAD

**Issue by xlXlSlayerlXlx** [supercrafter333/theRankShop#18]
Cuando compras elWhen buying a rank the server shuts down

**Comment by supercrafter333** [comment]
Please give more information.

**Comment by xlXlSlayerlXlx** [comment]
Error: [theRankShop] -> Can't find selected rank in RankManagementPlugin!
File: plugins/theRankShop (1).phar/src/supercrafter333/theRankShop/Forms/theRankShopDefaultForms
Line: 91
Type: pocketmine\utils\AssumptionFailedError
Backtrace:
#0 plugins/theRankShop (1).phar/src/supercrafter333/theRankShop/Forms/theRankShopDefaultForms(65): supercrafter333\theRankShop\Forms\theRankShopDefaultForms->openRankBuyForm(string[8] Membro I)
#1 plugins/theRankShop (1).phar/src/supercrafter333/theRankShop/libs/jojoe77777/FormAPI/Form(46): supercrafter333\theRankShop\Forms\theRankShopDefaultForms->supercrafter333\theRankShop\Forms\{closure}(object pocketmine\player\Player#176789, string[8] Membro I)
#2 pmsrc/src/player/Player(2117): supercrafter333\theRankShop\libs\jojoe77777\FormAPI\Form->handleResponse(object pocketmine\player\Player#176789, string[8] Membro I)
#3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(970): pocketmine\player\Player->onFormSubmit(int 1, int 2)
#4 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#129024)
#5 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#192928)
#6 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#129024, string[7] e...2..)
#7 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[10] cOedd2.b..)
#8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[19] ........:.!.x..nG.n)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#193218)
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#13 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688406880.9235)
#14 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#4, object pocketmine\utils\MainLogger#5, string[16] /home/container/, string[24] /home/container/plugins/)
#16 pmsrc/src/PocketMine(357): pocketmine\server()
#17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[82]     }
[83] 
[84]     /**
[85]      * @param string $rankName
[86]      * @return SimpleForm
[87]      */
[88]     public function openRankBuyForm(string $rankName)
[89]     {
[90]         $rank = RankManagementPluginMgr::getRankPlugin()->getRank($rankName);
[91]         if ($rank == null) throw new AssumptionFailedError("[theRankShop] -> Can't find selected rank in RankManagementPlugin!");
[92]         $rankInfo = new RankInfo($rankName);
[93]         $player = $this->player;
[94]         $form = new SimpleForm(function (Player $player, $data = null) use ($rankName, $rankInfo, $rank) {
[95]             $result = $data;
[96]             if ($result === null || $result === "") {
[97]                 $this->closed();
[98]                 return;
[99]             }
[100]             if ($result == "cancel") {
[101]                 $player->sendMessage(str_replace(["{rank}"], [$rankName], LanguageMgr::getMsg(Messages::FORMS_BUYRANK_CANCELBUY_MSG)));

**Comment by xlXlSlayerlXlx** [comment]
It is installed Ranksytem, GroupSytem, EconomyAPI and BedrockEconomy And always gives this error, I did the same ta explained on wiki

**Comment by supercrafter333** [comment]
That's still your fault - NOT MINE! You're trying to open the buy-form (buy-ui) of a non-existing rank. You have to edit `ranks.yml` or add the rank to your rank-management-plugin!

The error you got is called by theRankShop to prevent bugs.
If you can't fix it, please contact me on Discord: [`supercrafter333`](https://discord.com/users/supercrafter333)
