### ISSUE TITLE
Requests for the plugin (Rank upgrade, Buyer protection)

### ISSUE THREAD

**Issue by Ju999** [supercrafter333/theRankShop#7]
Hey, 
I tested your plugin, and it worked really well.
I have a few suggestions, so your plugin gets even better!
First, I would love to see a feature, where you can upgrade your rank (If you already have one, then the price for the more expensive ones go down by the price of your own rank)

Another request would be a feature, that protects you from buying a cheaper rank then you already have.
Thanks for this great plugin!

**Comment by supercrafter333** [comment]
Done in [0c51549](https://github.com/supercrafter333/theRankShop/commit/0c515499f09409cb7046c7c3df9d2df8474fcaf7)
