### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by xTERx69** [supercrafter333/theRankShop#8]
#0 pmsrc/src/utils/Config(121): pocketmine\utils\Config->load(string[52] D:/Bedrock Szerver/plugin_data/theRankShop/ranks.yml, integer 2, array[0])
#1 plugins/theRankShop.phar/src/supercrafter333/theRankShop/theRankShop(133): pocketmine\utils\Config->__construct(string[52] D:/Bedrock Szerver/plugin_data/theRankShop/ranks.yml, integer 2)
#2 plugins/theRankShop.phar/src/supercrafter333/theRankShop/Manager/RankMgr(21): supercrafter333\theRankShop\theRankShop::getRankCfg()
#3 plugins/theRankShop.phar/src/supercrafter333/theRankShop/Forms/theRankShopDefaultForms(70): supercrafter333\theRankShop\Manager\RankMgr::getAllRanksInConfig()
#4 plugins/theRankShop.phar/src/supercrafter333/theRankShop/Commands/theRankShopCommand(51): supercrafter333\theRankShop\Forms\theRankShopDefaultForms->openMenuForm()
#5 pmsrc/src/command/SimpleCommandMap(220): supercrafter333\theRankShop\Commands\theRankShopCommand->execute(object pocketmine\player\Player#29387, string[11] therankshop, array[0])
#6 pmsrc/src/Server(1408): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#29387, string[11] therankshop)
#7 pmsrc/src/player/Player(1382): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#29387, string[11] therankshop)
#8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(754): pocketmine\player\Player->chat(string[12] /therankshop)
#9 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(51): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#120216)
#10 pmsrc/src/network/mcpe/NetworkSession(397): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#98497)
#11 pmsrc/src/network/mcpe/NetworkSession(360): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#120216, string[33] M./therankshop.i@<.x....8S\......)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[36] S.../.H-J...../`.t.9S....>..........)
#13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[45] .q7`l}......n..,.$....OV..].L..S...WP.1.M].D=)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#27864)
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#17 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1646562467.5882)
#18 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
#19 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[19] D:\Bedrock Szerver\, string[27] D:\Bedrock Szerver\plugins\)
#20 pmsrc/src/PocketMine(327): pocketmine\server()
#21 pmsrc(11): require(string[63] phar://D:/Bedrock Szerver/PocketMine-MP.phar/src/PocketMine.php)

**Comment by supercrafter333** [comment]
You did something wrong in your `ranks.yml` file.
